services:
  - type: web
    name: borst-alkarma-api
    env: node
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: PORT
        value: "10000"
      - key: DATABASE_URL
        value: "postgresql://postgres:steven01272944685@db.zqdsvesmmmatjtbldhov.supabase.co:5432/postgres"
      - key: JWT_SECRET
        value: "borst_alkarma_secret_key_2024"
      - key: VAPID_PUBLIC_KEY
        value: "BEJZ0VW5Fc3NsMPSUUjQFYohT-5HlpDNq93SC3M5Ubwx1tY5Jcdwx5NcShegINlz7WHbc-jvzLrR1c1ng-UxBM4"
      - key: VAPID_PRIVATE_KEY
        value: "sftnDOP6dZJvLd8vjb86wY0DDDAUrd96wVNmGwkNQrE"
